### ISSUE TITLE
Configuring the logger overrides what is configured in logging.config

### ISSUE THREAD

**Issue by theladyjaye** [nlsdfnbch/Pysher#11]
here:

https://github.com/nlsdfnbch/Pysher/blob/master/pysher/connection.py#L40-L43

The level is forced on the logger that is created.  This will override any configuration of the logger using the standard `logging.config` module, for example: `dictConfig` or `fileConfig`.

So for example, if I do this in my logging config:

```
'loggers': {
                'pysher.connection': {
                    'level': 'WARNING',
                    'handlers': ['stream'],
                    'propagate': 'no'
                }
            }
```
Even though I have explicitly specified the level I want, the act of initializing the `Connection` object overrides my decision silently.

My proposed solve for this problem is to just omit line 43:

https://github.com/nlsdfnbch/Pysher/blob/master/pysher/connection.py#L43

Then it will play nice the built in python logging/logging configuration system.

**Comment by theladyjaye** [comment]
Actually a backwards compatible solution that might be more appealing:

set this to `log_level=None` in the init kwargs
https://github.com/nlsdfnbch/Pysher/blob/master/pysher/connection.py#L10


```python
if log_level is not None:
    if log_level == logging.DEBUG:
            websocket.enableTrace(True)
        self.logger.setLevel(log_level)
```

or get the logger to see if it's been configured already to see if  it's level is `DEBUG` then only do the `websocket.enableTrace` after that test..

**Comment by deepbrook** [comment]
Hey @aventurella , thanks for reaching out!

So if I understand you correctly, the issue you're pointing out is that currently we need to explicitly pass the `log_level` kwarg to set it to anything other than `logging.INFO`, despite having set the log level previously in a global configuration, correct ?

**Comment by theladyjaye** [comment]
Yes, that’s the issue.

**Comment by theladyjaye** [comment]
So killing that kwarg, or setting it to None and only touch the logger if it’s not None would do the trick

**Comment by deepbrook** [comment]
Thanks for contributing! I'll close this once I've implemented this.
