### ISSUE TITLE
Cluster error

### ISSUE THREAD

**Issue by umbertix** [nlsdfnbch/Pysher#13]
When trying to use the example code it throws an error:
```
Connection: Connection opened
Connection: ping to pusher
Connection: Message - {"event":"pusher:error","data":{"code":4001,"message":"Did you forget to specify the cluster when creating the Pusher instance?  App key XXXXX does not exist in this cluster."}}
Connection: Received error 4001
Connection: Error is unrecoverable.  Disconnecting
Callback raised unhandled
```

After checking the code I can't see any cluster option for the Pusher constructor. :( Am I missing something? (I'm completly new to python)

**Comment by ashwinrrao** [comment]
@umbertix I faced a similar issue today. What fixed the issue was that I created a new app in pusher and selected the cluster as mt1 (US East N.Virginia)

**Comment by umbertix** [comment]
Thx, that seem to do the trick. Still this should be fixed. I would happily assist but my python knowledge is null.

Happy to run some testing if this get's implemented. Thx for the library btw :)

**Comment by Yvictor** [comment]
@umbertix 
@ashwinrrao 
#14

**Comment by deepbrook** [comment]
@Yvictor , cheers! Still needs some minor changes, but the contribution is very welcome!

**Comment by deepbrook** [comment]
#14 merged, this should be fixed on `master`. Will be release on pypi in the coming days.

**Comment by paszin** [comment]
I had the same issue, thanks for solving this one. Maybe a hint in the readme could save some time.
```
cluster = "mt1" # mt1 for N. Virginia, us2 for Ohio, eu for Ireland, ap1 for Singapore or ap2 for Mumbai
pusher = pysher.Pusher(key, cluster=cluster)
```
