### ISSUE TITLE
Connection.needs_reconnect isn't reset

### ISSUE THREAD

**Issue by jeffro256** [nlsdfnbch/Pysher#16]
Whenever `self.needs_reconnect` is set to `True` due to missed ping message or timing out, it never gets set back to `False`. I would recommend putting the line `self.needs_reconnect = False` in the method `Connection._on_open`. I might be misunderstanding the design incorrectly, but the way it is now will have `self.needs_reconnect` set to `True` after the socket has already reconnected and is receiving messages. Thanks for reading

**Comment by deepbrook** [comment]
the latest release, `pysher-1.0.0`, should take care of this!
