### ISSUE TITLE
Getting data in a variable

### ISSUE THREAD

**Issue by robinCantelli** [nlsdfnbch/Pysher#21]
Hey thanks for your skript!
I tries your code with a specific website (Bitstamp)

The data that is printed is some kind of a dictionary. what I want is to get that dict written on a variable to use it like My_dict = 'The data I'm receiving via websocket' and later work with pandas or indexing.

Thanks in advance!

Robin

PS:I don't see the difference between args and kwargs here.

my code just in case:

```python

import pysher
import sys
import time


import logging
root = logging.getLogger()
root.setLevel(logging.INFO)
ch = logging.StreamHandler(sys.stdout)
root.addHandler(ch)

pusher = pysher.Pusher('de504dc5763aeef9ff52')

def  my_func(*args, **kwargs):
    print("processing Args:", args)
    print("processing Kwargs:", kwargs)


def connect_handler(data):
    channel = pusher.subscribe('order_book')
    channel.bind('data', my_func)

pusher.connection.bind('pusher:connection_established', connect_handler)
pusher.connect()

while True:
	time.sleep(1)

```

**Comment by deepbrook** [comment]
Hey @robinCantelli ,
In order to work with the data I'd suggest storing it in a variable in your `my_func` method. 

```python

import pysher
import sys
import time


import logging
root = logging.getLogger()
root.setLevel(logging.INFO)
ch = logging.StreamHandler(sys.stdout)
root.addHandler(ch)

pusher = pysher.Pusher('de504dc5763aeef9ff52')

# Store all messages in a list to loop over later
data = []

def  my_func(*args, **kwargs):
    data.append([args, kwargs])


def connect_handler(data):
    channel = pusher.subscribe('order_book')
    channel.bind('data', my_func)

pusher.connection.bind('pusher:connection_established', connect_handler)
pusher.connect()

while True:
	time.sleep(1)

```

`*args` and `**kwargs` are safety implementations in order to work with whatever pusher channel you subscribe to - if you know you'll only have a single positional argument, defining `my_func` as follows is enough too:

```python
def my_func(message):
    print(message)
```

Hope that helps.

**Comment by robinCantelli** [comment]
Thank you so much!!!!

You can't imagine how much this is helping me!!!
Do you now how to switch of that it is printed in my console all the time? I'd like to see some other things on my console during the program is running.

Best

Robin

**Comment by deepbrook** [comment]
Sure! If you omit the logger definition, it should not give you any log messages - only stdout (i. e. print() calls) should be seen then.
