### ISSUE TITLE
Private Channel Error

### ISSUE THREAD

**Issue by ricardoperovano** [nlsdfnbch/Pysher#22]
Hi, i'm trying to subscribe to a private channel, but it gives me some error. I know what the error means I just needed to know how to send the right data on the request:
The error says:

"Auth value for subscription to private-message-answered-5 is invalid: should be of format 'key:signature'"

I need to call my auth endpoint that is /broadcast/auth, and I also need to pass a token on header, when calling the pusher.subscribe method

Does anybody knows how can I achieve that ?

**Comment by ricardoperovano** [comment]
I just got it working by making a normal post request to my api channel auth and then pass the received auth string to pusher.subscribe(channel_name=channel_name, auth=auth)

**Comment by birdlavv** [comment]
How did you get the initial `socket_id` to post to your `/broadcast/auth` endpoint to get the auth string?
