### ISSUE TITLE
Callback function not calling

### ISSUE THREAD

**Issue by ricardoperovano** [nlsdfnbch/Pysher#23]
I'm having problems to call a callback function when trying to subscribe to a channel. The loggin says it has successfuly connected, and I can receive the events on the logs, but the callback function has not been calling.

I made a test function but its not working. What am I doing wrong ?

**channel = self.pusher.subscribe(channel_name=channel_name, auth=auth)
        channel.bind('MessageAnswered', callback=self.teste)**

**Comment by deepbrook** [comment]
Hey @ricardoperovano ,
Thanks for using this fork! Regarding your issue:

Are you sure there's an event called `MessageAnswered` on the channel you subscribe to? What does `self.teste` look like? I can help you best if you provide a minimal working example.

**Comment by ricardoperovano** [comment]
Hy @nlsdfnbch , thanks for the answer. After your comment, i was able to realize that my event itself was not wrong, the name is MessageAnswered, but the problem was that I was receiving the full path of the class App\Events\MessageAnswered, since it was triggered by laravel, and I was just listening for MessageAnswere.

Now its working fine! Thankyou !
