### ISSUE TITLE
Bump version to 0.5.0 and upload to pypi (cluster support)

### ISSUE THREAD

**Issue by smvv** [nlsdfnbch/Pysher#26]
Is it possible to release version 0.5.0 on pypi? I would like to use the cluster support added in PR #14.

**Comment by deepbrook** [comment]
Ah yes - of course!
Sorry for the delay. I'll release a new version asap. Meanwhile, you can pip install from the repo as well! simply clone it and `pip install .` in its repository *should* work.

Cheers!

**Comment by deepbrook** [comment]
Done, 0.5.0 is now up on pypi.

**Comment by smvv** [comment]
@nlsdfnbch Thanks! I'm aware that you can install it locally. FYI you can also install a git commit using pip, e.g.: https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch#20101940. However, `pipenv` has had a bug where installing a specific git commit that is also satisfied by a thirdparty's dependency of an official version will choose the thirdparty's official version. In the end, it resulted a mess in my continuous integration environment when I had to use any non-published pypi package.
