### ISSUE TITLE
v1.x doesn't work for me

### ISSUE THREAD

**Issue by dustyrock** [nlsdfnbch/Pysher#40]
I have tried version 1 and 1.02 but can not connect to pusher and get following error messages:

error from callback <bound method Connection._on_open of <Connection(Thread-1, started daemon 140250322847488)>>: _on_open() missing 1 required positional argument: 'ws'
error from callback <bound method Connection._on_message of <Connection(Thread-1, started daemon 140250322847488)>>: _on_message() missing 1 required positional argument: 'message'

**Comment by deepbrook** [comment]
What's your `websocket-client` version? (`pip freeze | grep websocket-client` on linux)

They did some mumbo jumbo in the releases since `0.49.0`, but the latest version should work with Pysher.

**Comment by dustyrock** [comment]
Thanks for your quick response and hint!

I didn't have the latest version of the websocket-client installed, but I think it was already 0.5.
I now have updated to the latest version 0.53 and updated all related python modules too.
Unfortunately I still get the same type of errors.

Maybe something in my environment is still wrong.
Do I have to adapt my pusher client code in some special way when changing to pysher version 1.x?

**Comment by agronholm** [comment]
Fixed in 1.0.4 (via 8bec81616be2b6c9a9c0e2774b42890426a73745).
