### ISSUE TITLE
not working with last version

### ISSUE THREAD

**Issue by twisted-Sonnet** [nlsdfnbch/Pysher#41]
working with Pysher 1.0.1
not working with Pysher 1.0.2 and 1.0.3
websocket-client 0.53

Please help :)

```
import pysher, json, time


def callback(data):
    event = json.loads(data)
    print(event)


def connection_callback(data):
    channel = pusher.subscribe("inventory_changes")
    channel.bind("listed", callback)
    channel.bind("price_changed", callback)
    channel.bind("delisted_or_sold", callback)
    channel.bind("extra_info", callback)


pusher = pysher.Pusher(key='c0eef4118084f8164bec65e6253bf195', custom_host='notifier.bitskins.com', port=443)
pusher.connection.bind("pusher:connection_established", connection_callback)
pusher.connect()

while True:
    time.sleep(1)

**Comment by x-Sonnet** [comment]
import pysher, json, time


def callback(data):
    event = json.loads(data)
    print(event)


def connection_callback(data):
    channel = pusher.subscribe("inventory_changes")
    channel.bind("listed", callback)
    channel.bind("price_changed", callback)
    channel.bind("delisted_or_sold", callback)
    channel.bind("extra_info", callback)


pusher = pysher.Pusher(key='c0eef4118084f8164bec65e6253bf195', custom_host='notifier.bitskins.com', port=443)
pusher.connection.bind("pusher:connection_established", connection_callback)
pusher.connect()

while True:
    time.sleep(1)

**Comment by x-Sonnet** [comment]
working with Pysher 1.0.1
not working with Pysher 1.0.2 and 1.0.3
websocket-client 0.53
