### ISSUE TITLE
Since Version 1.0.2 the script never connect

### ISSUE THREAD

**Issue by scdias** [nlsdfnbch/Pysher#43]
the last version that the script worked are:
pkg-resources==0.0.0
Pysher==1.0.1
six==1.11.0
websocket-client==0.53.0

since 1.0.2 the "pusher.connection.state" always return "connecting"

[__main__.py.txt](https://github.com/nlsdfnbch/Pysher/files/2416903/__main__.py.txt)

**Comment by agronholm** [comment]
In Pysher 1.0.2, a change was introduced that added callback arguments that are never passed to them, thus breaking the whole library.

**Comment by scdias** [comment]
Working with Pysher==1.0.4
