### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by twisted-Sonnet** [nlsdfnbch/Pysher#44]
Lately I periodically get an error like this. What is the reason for this?
Pysher 1.0.1 (cuz 1.0.2 and 1.0.3 not working for me. I don't know why)
websocket-client 0.53

`ERROR:websocket:error from callback <bound method Connection._on_message of <Connection(PysherEventLoop, started daemon 8476)`

**Comment by agronholm** [comment]
See #43 for an explanation.

**Comment by agronholm** [comment]
Fixed in 1.0.4 (via 8bec81616be2b6c9a9c0e2774b42890426a73745).

**Comment by twisted-Sonnet** [comment]
v1.0.4 gets this error too =(

**Comment by agronholm** [comment]
Then I was mistaken. Is this the complete error message? There is no traceback or anything?

**Comment by agronholm** [comment]
Have you tried earlier versions of Pysher?

**Comment by twisted-Sonnet** [comment]
this error type just spams for every event
`ERROR:websocket:error from callback <bound method Connection._on_message of <Connection(PysherEventLoop, started daemon 14604)>>: 'Sealed Graffiti | King Me (SWAT Blue)'
INFO:pysher.connection:Connection: Message - {"event":"price_changed","data":"{\"app_id\":\"730\",\"context_id\":\"2\",\"item_id\":\"14347029788\",\"asset_id\":\"14347029788\",\"class_id\":\"2770787372\",\"instance_id\":\"0\",\"market_hash_name\":\"Spectrum 2 Case\",\"image\":\"https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFY4naeaJGhGtdnmx4Tek_bwY-iFlGlUsJMp3LuTot-mjFGxqUttZ2r3d4eLMlhpnZPxZK0/256fx256f\",\"price\":\"0.01\",\"old_price\":\"4985.11\",\"discount\":\"0\",\"withdrawable_at\":1523084399,\"event_type\":\"price_changed\",\"broadcasted_at\":1537798416.94977}","channel":"inventory_changes"}
ERROR:websocket:error from callback <bound method Connection._on_message of <Connection(PysherEventLoop, started daemon 14604)>>: 'Spectrum 2 Case'
INFO:pysher.connection:Connection: Message - {"event":"extra_info","data":"{\"app_id\":\"730\",\"context_id\":\"2\",\"item_id\":\"14890204436\",\"asset_id\":\"14890204436\",\"extra_info\":{\"paintindex\":46,\"paintseed\":555,\"rarity\":1,\"quality\":4,\"paintwear\":1060414874,\"patternname\":\"Contractor\"},\"wear_value\":\"0.7056518793106079\",\"sticker_info\":{},\"event_type\":\"extra_info\"}","channel":"inventory_changes"}
INFO:pysher.connection:Connection: Message - {"event":"price_changed","data":"{\"app_id\":\"730\",\"context_id\":\"2\",\"item_id\":\"14805638728\",\"asset_id\":\"14805638728\",\"class_id\":\"3000354341\",\"instance_id\":\"188530170\",\"market_hash_name\":\"★ StatTrak™ Karambit | Slaughter (Minimal Wear)\",\"image\":\"https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpovbSsLQJf2PLacDBA5ciJlY20jfL2IbrummJW4NE_0rGVoNvzilG3qkduNmCnd4eSdAE3aVuD_Ve8wOe7hpLuuJuYmyRivj5iuyi_zJQcBA/256fx256f\",\"price\":\"246.01\",\"old_price\":\"246.02\",\"discount\":\"0\",\"withdrawable_at\":1536735599,\"event_type\":\"price_changed\",\"broadcasted_at\":1537798418.39264}","channel":"inventory_changes"}
ERROR:websocket:error from callback <bound method Connection._on_message of <Connection(PysherEventLoop, started daemon 14604)>>: '★ StatTrak™ Karambit | Slaughter (Minimal Wear)'
INFO:pysher.connection:Connection: Message - {"event":"listed","data":"{\"app_id\":\"433850\",\"context_id\":\"1\",\"item_id\":\"169263449112664181\",\"asset_id\":\"169263449112664181\",\"class_id\":\"1544464977\",\"instance_id\":\"0\",\"phase\":null,\"image\":\"https://steamcommunity-a.akamaihd.net/economy/image/iGm5OjgdO5r8OoJ7TJjS39tTyGCTzzQwmWl1QPRXu8oaf69-NOHLAbqw_23aLe8AcRQ8-3uyKA7_CGvsJYds9U65FMF7i6AbXTJ-DAS_wX5ZIoiWVOuw8TLwyznlPZKg/257fx257f\",\"market_hash_name\":\"Wildstyle AR-15\",\"price\":\"1.78\",\"discount\":\"33\",\"withdrawable_at\":1537798416,\"event_type\":\"listed\",\"broadcasted_at\":1537798418.51554}","channel":"inventory_changes"}
ERROR:websocket:error from callback <bound method Connection._on_message of <Connection(PysherEventLoop, started daemon 14604)>>: 'Wildstyle AR-15'
INFO:pysher.connection:Connection: Message - {"event":"listed","data":"{\"app_id\":\"730\",\"context_id\":\"2\",\"item_id\":\"14652667946BSL542211083\",\"asset_id\":\"14652667946\",\"class_id\":\"2924390940\",\"instance_id\":\"143865972\",\"phase\":null,\"image\":\"https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXX7gNTPcUxuxpJSXPbQv2S1MDeXkh6LBBOiev3ZV851qOaJ28RvInuxIWPw_WtMr-Gkz0FvZwh27mU8Yqm3APir0VrYm3tZNjC3MZhHzk/257fx257f\",\"market_hash_name\":\"Chroma 3 Case Key\",\"price\":\"2.94\",\"discount\":\"0\",\"withdrawable_at\":1532501999,\"event_type\":\"listed\",\"broadcasted_at\":1537798418.5194}","channel":"inventory_changes"}
ERROR:websocket:error from callback <bound method Connection._on_message of <Connection(PysherEventLoop, started daemon 14604)>>: 'Chroma 3 Case Key'
INFO:pysher.connection:Connection: Message - {"event":"listed","data":"{\"app_id\":\"730\",\"context_id\":\"2\",\"item_id\":\"14861440468BSL541284254\",\"asset_id\":\"14861440468\",\"class_id\":\"3018955658\",\"instance_id\":\"480085569\",\"phase\":null,\"image\":\"https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot7HxfDhjxszJemkV08y5nY6fqPP9ILrDhGpI18l4jeHVu4702FLiqBA4MDv6JYHEIwRsNQ3Srwe-wu_t1pO76JrPyiNlu3Qh4X7D30vg5znacIE/257fx257f\",\"market_hash_name\":\"AK-47 | Point Disarray (Minimal Wear)\",\"price\":\"17.84\",\"discount\":\"14\",\"withdrawable_at\":1538031599,\"event_type\":\"listed\",\"broadcasted_at\":1537798418.52158}","channel":"inventory_changes"}
ERROR:websocket:error from callback <bound method Connection._on_message of <Connection(PysherEventLoop, started daemon 14604)>>: 'AK-47 | Point Disarray (Minimal Wear)'
INFO:pysher.connection:Connection: Message - {"event":"extra_info","data":"{\"app_id\":\"730\",\"context_id\":\"2\",\"item_id\":\"14890204453\",\"asset_id\":\"14890204453\",\"extra_info\":{\"paintindex\":0,\"paintseed\":null,\"rarity\":1,\"quality\":4,\"paintwear\":null},\"wear_value\":\"-1\",\"sticker_info\":{},\"event_type\":\"extra_info\"}","channel":"inventory_changes"}
INFO:pysher.connection:Connection: Message - {"event":"price_changed","data":"{\"app_id\":\"730\",\"context_id\":\"2\",\"item_id\":\"14808616965\",\"asset_id\":\"14808616965\",\"class_id\":\"3001396235\",\"instance_id\":\"188530170\",\"market_hash_name\":\"StatTrak™ FAMAS | Afterimage (Well-Worn)\",\"image\":\"https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposLuoKhRf0Ob3cy9N59m4q5CKg__LNbrcl3hu5cB1g_zMu46h2Ffn80Nuaz-icoGdJwRoNV_YqVbvyb_q05-5tM7Pyns2vSYltn_D30vguOQHaXs/256fx256f\",\"price\":\"10.50\",\"old_price\":\"10.45\",\"discount\":\"0\",\"withdrawable_at\":1536735599,\"event_type\":\"price_changed\",\"broadcasted_at\":1537798419.53914}","channel":"inventory_changes"}
ERROR:websocket:error from callback <bound method Connection._on_message of <Connection(PysherEventLoop, started daemon 14604)>>: 'StatTrak™ FAMAS | Afterimage (Well-Worn)'
INFO:pysher.connection:Connection: Message - {"event":"extra_info","data":"{\"app_id\":\"730\",\"context_id\":\"2\",\"item_id\":\"14890204473\",\"asset_id\":\"14890204473\",\"extra_info\":{\"paintindex\":46,\"paintseed\":210,\"rarity\":1,\"quality\":4,\"paintwear\":1060815011,\"patternname\":\"Contractor\"},\"wear_value\":\"0.7295019030570984\",\"sticker_info\":{},\"event_type\":\"extra_info\"}","channel":"inventory_changes"}
INFO:pysher.connection:Connection: Message - {"event":"price_changed","data":"{\"app_id\":\"730\",\"context_id\":\"2\",\"item_id\":\"14629366310\",\"asset_id\":\"14629366310\",\"class_id\":\"2914201702\",\"instance_id\":\"188530170\",\"market_hash_name\":\"StatTrak™ USP-S | Serum (Field-Tested)\",\"image\":\"https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoo6m1FBRp3_bGcjhQ0927q4WHkvTgIbLSqXlU7Pp8j-3I4IG7jQSy_ktpYGCgdoeRc1U7NVGD_QPrkunp157uvM6dy3E16yUm5S2Llwv330-mWSJKYQ/256fx256f\",\"price\":\"13.51\",\"old_price\":\"13.58\",\"discount\":\"0\",\"withdrawable_at\":1531810799,\"event_type\":\"price_changed\",\"broadcasted_at\":1537798420.28199}","channel":"inventory_changes"}
ERROR:websocket:error from callback <bound method Connection._on_message of <Connection(PysherEventLoop, started daemon 14604)>>: 'StatTrak™ USP-S | Serum (Field-Tested)'
INFO:pysher.connection:Connection: Message - {"event":"price_changed","data":"{\"app_id\":\"730\",\"context_id\":\"2\",\"item_id\":\"14752502451\",\"asset_id\":\"14752502451\",\"class_id\":\"2974962007\",\"instance_id\":\"188530139\",\"market_hash_name\":\"Souvenir Sawed-Off | Amber Fade (Factory New)\",\"image\":\"https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpopbuyLgNv1fX3cDx96t2ykb-GkuP1P7fYlVRd4cJ5nqfA9Nuh2Qzm-0VlZmqmcILHdQE-ZgyEqAK2xOe915fp7pqbn3Qws3Fw-z-DyIWEAXkH/256fx256f\",\"price\":\"0.98\",\"old_price\":\"0.89\",\"discount\":\"0\",\"withdrawable_at\":1535353199,\"event_type\":\"price_changed\",\"broadcasted_at\":1537798420.28303}","channel":"inventory_changes"}`

**Comment by twisted-Sonnet** [comment]
I previously used v1.0.1
v1.0.2 and 1.0.3 not worked for me

**Comment by twisted-Sonnet** [comment]
![image](https://user-images.githubusercontent.com/42423011/46513114-d2ddce00-c85f-11e8-99c2-da06db5cf666.png)

**Comment by agronholm** [comment]
Have you tried to track down the source of the errors? It doesn't seem obvious from the log.

**Comment by deepbrook** [comment]
@x-Sonnet, are you positive the only change were the pysher versions? If you downgrade to `1.0.1` it still works?
From what you've posted, it looks like the errors are due to a keyError or similar.
