### ISSUE TITLE
Unsatisfied requirements when upgrading to 1.0.4 from 0.5.0

### ISSUE THREAD

**Issue by dorinand** [nlsdfnbch/Pysher#46]
Hello, I used Pysher==0.5.0. I upgraded to version 1.0.4 but I did not received new messages from websocket. The problem was with unsatisfied version of websocket-client. In requirements.txt is mentioned websocket-client==0.51.0 but I had only 0.48.0. I think, it should be updated properly when installed new version of Pysher or at least, it should informed me about unmatching versions. This is what I received when I installed Pysher version 1.0.4.

```
pip3 install Pysher==1.0.4
Collecting Pysher==1.0.4
  Using cached https://files.pythonhosted.org/packages/0e/ca/0e4b7d71944e6244da5fdccca51bb49e047fe295925e899776b919f6e638/Pysher-1.0.4-py3-none-any.whl
Requirement already satisfied: websocket-client!=0.49 in /usr/local/lib/python3.6/dist-packages (from Pysher==1.0.4)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from websocket-client!=0.49->Pysher==1.0.4)
Installing collected packages: Pysher
  Found existing installation: Pysher 0.5.0
    Uninstalling Pysher-0.5.0:
      Successfully uninstalled Pysher-0.5.0
Successfully installed Pysher-1.0.4
```
According to me, it should not print Requirements already satisfied.

When I installed websocket-client=0.51.0, it works without any problem.
When I installed (without upgrade) Pysher==1.0.4 in new virtual env , it works without any problem.

**Comment by deepbrook** [comment]
Hey @dorinand !

That looks like an issue with `pip --upgrade`,  not Pysher - I updated the requirements with the latest release.

But thanks for reaching out!
