### ISSUE TITLE
Channel callback doesn't fire

### ISSUE THREAD

**Issue by wkyle** [nlsdfnbch/Pysher#6]
Tried implementing basic example. The 'data' event doesn't seem to be firing.

```
import pysher
import time

def channel_callback(data):
    print(data)

def connection_callback(data):
    channel = pusher.subscribe("order_book_BTC_USD")
    channel.bind("data", channel_callback)
    
pusher = pysher.Pusher("de504dc5763aeef9ff52")
pusher.connection.bind("pusher:connection_established", connection_callback)
pusher.connect()

while True:
    time.sleep(1)
```

**Comment by wkyle** [comment]
To follow up on this, I wrote a `print(message)` inside the `_on_message` handler in connections.py and while it prints the initial connection messages, there are no messages following that. Trades are occurring on BitStamp at the moment however no messages are coming through.

**Comment by deepbrook** [comment]
Hey @wkyle,
your orderbook channel is wrong. it should be `order_book`, not `order_book_BTC_USD`.

Cheers!
Nils

**Comment by wkyle** [comment]
Oh my. After all that I misread the BitStamp documentation. 
Thank you kindly. I look forward to following this project.
Wes
